config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('ranking/',include('ranking.urls')),
]

ranking/urls.py
from django.urls import path
from . import views

app_name = 'ranking'

urlpatterns = [
    path('', views.RankingList.as_view(), name='ranking_list'),
]

ranking/models.py
from django.db import models

# Create your models here.
class Problem(models.Model):
    problem_id = models.CharField('問題ID', max_length=255, unique=True)
    problem_name = models.CharField('問題名', max_length=255)
    contest_id = models.CharField('コンテストID',max_length=255)
    contest_name = models.CharField('コンテスト名',max_length=255)

    def __str__(self):
        return 'コンテスト名:{} 問題名:{}'.format(self.contest_name, self.problem_name)

class Submission(models.Model):
    submission_id = models.CharField('提出ID', max_length=255, unique=True)
    problem = models.ForeignKey(Problem, verbose_name='問題', on_delete=models.PROTECT)
    submitter_accepted = models.IntegerField('提出者AC数')
    submitted_at = models.DateTimeField('提出日時')

    def __str__(self):
        return '問題名:{} 提出者AC数:{}　時刻:{}'.format(self.problem.problem_name, self.submitter_accepted, self.submitted_at)

ranking/views.py
from django.views import generic
from django.db.models import Count
from ranking.models import Submission
from django.utils import timezone
import datetime

# Create your views here.
class RankingList(generic.ListView):
    model = Submission
    template_name = "ranking/ranking_list.html"
    context_object_name = "ranking_list"
    ordering = "-total"
    start_period = None
    end_period = None
    submit_count = -1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_list"] = {
            "all":"ALL",
            "0":"0～199",
            "200":"200～399",
            "400":"400～599",
            "600":"600～799",
            "800":"800～999",
            "1000":"1000～",
        }
        context["period_list"] = [str(period) for period in range(1, 31)]
        context["start_period"] = self.start_period
        context["end_period"] = self.end_period
        context["submit_count"] = self.submit_count

        return context

    def get_queryset(self):
        if self.queryset is not None:
            queryset = self.queryset
        elif self.model is not None:
            queryset = self.model.objects.all()

        FILTER_RANGE = {
            "all":{"lower":0, "upper":10000000},
            "0":{"lower":0, "upper":199},
            "200":{"lower":200, "upper":399},
            "400":{"lower":400, "upper":599},
            "600":{"lower":600, "upper":799},
            "800":{"lower":800, "upper":999},
            "1000":{"lower":1000, "upper":10000000}
        }

        filter = self.request.GET.get("filter")
        period = self.request.GET.get("period")

        # パラメータが正常かどうかを確認する
        if filter not in FILTER_RANGE:
            return self.model.objects.none()
        if not period.isdecimal():
            return self.model.objects.none()

        period = int(period)

        if period < 1 or period > 30:
            return self.model.objects.none()

        filter = FILTER_RANGE[filter]

        # AC数で絞り込み
        queryset = queryset.filter(submitter_accepted__gte=filter["lower"],
                                    submitter_accepted__lte=filter["upper"])

        # 提出時刻で絞り込み
        now_utc = timezone.now()
        now_jst = now_utc.astimezone(datetime.timezone(datetime.timedelta(hours=9)))
        to_jst = datetime.datetime(now_jst.year, now_jst.month, now_jst.day, 0, 0, 0, 0,
                                    tzinfo=datetime.timezone(datetime.timedelta(hours=9)))
        from_jst = to_jst - datetime.timedelta(days=period)
        queryset = queryset.filter(submitted_at__gte=from_jst,
                                    submitted_at__lt=to_jst)

        self.start_period = from_jst
        self.end_period = to_jst
        self.submit_count = queryset.count()

        # check
        print(queryset.order_by("submitted_at")[:1])
        print(queryset.order_by("-submitted_at")[:1])

        # 問題ごとの提出されたコード数の情報を持つquerysetを作成
        queryset = queryset.select_related().values(
            "problem",
            "problem__problem_id",
            "problem__problem_name",
            "problem__contest_id",
            "problem__contest_name"
            ).annotate(total=Count("submission_id"))
        
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
            
        # 上位100問を表示
        return queryset[:100]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="AtCoder Hot Problemsは前日に提出されたコードを全て集計し、どの問題が多く取り組まれたかをランキングにして表示するWebアプリケーションです。">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AtCoder Hot Problems</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header class="site-header wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'ranking:ranking_list' %}">AtCoder Hot Problems</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Links
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="https://github.com/reiyiyi/AtCoder-Hot-Problems-Ver2.0-" target="_blank">GitHub</a></li>
                                <li><a class="dropdown-item" href="https://twitter.com/Re_code_A" target="_blank">@Re_code_A</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

templates/ranking/ranking_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form action="" method="get">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-3">
                <div class="mb-3">
                    <label for="filter" class="form-label">AC数:</label>
                    <select name="filter" class="form-select">
                        {% if request.GET.filter == "" or request.GET.filter == None %}
                        <option value="" selected>---</option>
                        {% else %}
                        <option value="">---</option>
                        {% endif %}
                        {% for filter, filter_name in filter_list.items %}
                        {% if filter == request.GET.filter %}
                        <option value="{{ filter }}" selected>{{ filter_name }}</option>
                        {% else %}
                        <option value="{{ filter }}">{{ filter_name }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="mb-3">
                    <label for="period" class="form-label">集計期間(日):</label>
                    <select name="period" class="form-select">
                        {% if request.GET.period == "" or request.GET.period == None %}
                        <option value="" selected>---</option>
                        {% else %}
                        <option value="">---</option>
                        {% endif %}
                        {% for period in period_list %}
                        {% if period == request.GET.period %}
                        <option value="{{ period }}" selected>{{ period }}</option>
                        {% else %}
                        <option value="{{ period }}">{{ period }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md" style="text-align: center;">
                <button type="submit" class="btn btn-danger">ランキング表示</button>
            </div>
        </div>
    </div>
</form>
<hr>
{% if request.GET.filter == "" or request.GET.period == "" or request.GET.filter == None or request.GET.period == None %}
<p>AC数と集計期間を選択して、ランキングを見てみましょう！</p>

<div class="card">
    <div class="card-header">
        AC数 とは
    </div>
    <div class="card-body">
        <p>例えば、上記のAC数の0~199と書かれた項目を選択すると、AtCoderにて今まで正解した問題の数が0以上199以下の方々が集計期間内に提出したコードのみを集計したランキングを閲覧することができます。</p>
        <p>そのため、「最近AtCoderを始めたけど、どういった問題を選んで取り組めばよいのかわからない」という悩みを少しでも抱えている方はこのランキングから、自分と同じくらいのAC数の人たちが取り組んでいる問題を見て、どの問題を選んで解くかを決める1つの参考材料にして欲しいと願っています。</p>
    </div>
</div>

{% elif ranking_list|length == 0 %}
<p>総コード数：{{ submit_count }}</p>
<p style="text-align: right;">集計期間：{{ start_period }}～{{ end_period }}</p>
<p>データが見つかりませんでした</p>
{% else %}
<p>総コード数：{{ submit_count }}</p>
<p style="text-align: right;">集計期間：{{ start_period }}～{{ end_period }}</p>
<table class="table table-striped" border="1">
    <tr>
        <th scope="col">順位</th>
        <th scope="col">コンテスト名</th>
        <th scope="col">問題名</th>
        <th scope="col">コード数</th>
    </tr>
    {% for data in ranking_list %}
    <tr>
        <td>{{ forloop.counter }}位</td>
        <td><a href="https://atcoder.jp/contests/{{ data.problem__contest_id }}" target="_blank">{{ data.problem__contest_name }}</a></td>
        <td><a href="https://atcoder.jp/contests/{{ data.problem__contest_id }}/tasks/{{ data.problem__problem_id }}" target="_blank">{{ data.problem__problem_name }}</a></td>
        <td>{{ data.total }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}